theme: jekyll-theme-slate
title: Welcome to Calvin's homepage!
description: My name is Calvin Vong. I am a senior at Univeristy of Nebraska at Omaha (UNO) studying Management Information Systems. This is
        my last semester at UNO. I am creating this page for my ISQA3900 class. This page is created to demostrate my skills using HTML and CSS.
        While working towards my degree, I currently have an internship at Proxibid where
        I mainly work with servers and databases. On my free time, I like to be outdoors or traveling around the world.
        In the last year, I have been to 14 countries.
